=== adr/yadr/schemas/other-yaml-templates/y-statement-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "metadata": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "author": {
          "type": "string"
        },
        "date": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "title"
      ]
    },
    "context": {
      "type": "string"
    },
    "facing": {
      "type": "array",
      "items": 
        {
          "type": "string"
        }
      
    },
    "decided-for": {
      "type": "string"
    },
    "neglected": {
      "type": "array",
      "items": 
        {
          "type": "string"
        }
      
    },
    "to-achieve": {
      "type": "array",
      "items":
        {
          "type": "string"
        }
    },
    "accepting-that": {
      "type": "array",
      "items":
        {
          "type": "string"
        }
    },
    "additional-rationale": {
      "type": "string"
    }
  },
  "required": [
    "context",
    "facing",
    "decided-for",
    "to-achieve",
    "accepting-that"
  ]
}

=== adr/yadr/examples-validation/other-yaml-templates/yaml-as-additional-y-statement-syntax-AD-002.json
{
  "metadata": {
    "id": "AD-002",
    "author": "OZ",
    "date": "2026-03-07",
    "version": "1.1",
    "title": "Render Y-Statements in YAML",
    "related": "AD-001"
  },
  "context": "\nY-statement ADRs need a concrete syntax that can be parsed and validated.\n",
  "facing": [
    "Effort to create and maintain",
    "Readability"
  ],
  "decided-for": "Yet another markup language (YAML)",
  "neglected": [
    "Plain text",
    "Markdown",
    "JSON"
  ],
  "to-achieve": [
    "A healthy balance between cost and benefit",
    "Being able to show something new",
    "Include those on the team who are familiar with \"YAML\""
  ],
  "accepting-that": [
    "AD consumers not familiar with YAML might complain"
  ],
  "additional-rationale": "technology exploration | increase visibility and community outreach"
}

=== adr/yadr/examples-validation/other-yaml-templates/yaml-as-additional-y-statement-syntax-AD-001.json
{
  "metadata": {
    "id": "AD-001",
    "author": "OZ",
    "date": "2026-03-09",
    "version": "1.1",
    "title": "Use Y-Statements"
  },
  "context": "Need for an ADR template for our project; many exist",
  "facing": [
    "Effort to create and maintain",
    "Readability"
  ],
  "decided-for": "Y-Statements, in this new YAML template",
  "neglected": [
    "Nygardian ADRs",
    "MADR full or light",
    "others"
  ],
  "to-achieve": [
    "A healthy balance between cost and benefit",
    "Being able to show something new",
    "Include those on the team who are familiar with YAML"
  ],
  "accepting-that": [
    "Markdown/MADR guys have to be retrained (just a bit)"
  ],
  "additional-rationale": "\nADRs are great to have, many templates are suited. ADRs keep you CALM, see various blog posts <<https://medium.com/olzzio/y-statements-10eb07b5a177> and [\"Y-Statements --- A light template for architectural decision capturing\"](https://medium.com/olzzio/y-statements-10eb07b5a177) # optional\n"
}
